import type { CSSProperties } from "react";

const sudanTheme = {
  family: "nile-flag",
  background: "flag-spectrum",
  flag: {
    black: "#050608",
    blackRgb: "5 6 8",
    white: "#f5f7f4",
    whiteRgb: "245 247 244",
    red: "#d23449",
    redRgb: "210 52 73",
    green: "#0d7a43",
    greenRgb: "13 122 67",
  },
  tone: {
    deepRgb: "7 8 10",
    surfaceRgb: "14 17 20",
    raisedRgb: "22 26 30",
  },
  color: {
    bg: "#06080a",
    bgTop: "#13171b",
    bgDeep: "#020304",
    foreground: "#f5f7f4",
    foregroundSoft: "#dde2dd",
    muted: "#a8b0aa",
    primary: "#0d7a43",
    primarySoft: "#61c48b",
    primaryStrong: "#afe3c4",
    secondary: "#d23449",
    secondarySoft: "#f27b8f",
    surface: "rgba(14, 17, 20, 0.82)",
    surfaceStrong: "rgba(8, 10, 12, 0.94)",
    surfaceAccent: "rgba(17, 22, 19, 0.88)",
    surfaceMedia: "rgba(8, 10, 12, 0.95)",
    borderSoft: "rgba(245, 247, 244, 0.12)",
    borderStrong: "rgba(245, 247, 244, 0.22)",
    gridLine: "rgba(245, 247, 244, 0.06)",
    glow: "rgba(210, 52, 73, 0.34)",
  },
  chrome: {
    headerSurface: "rgba(9, 11, 13, 0.84)",
    headerBorder: "rgba(245, 247, 244, 0.11)",
    headerShadow: "0 24px 70px rgba(0, 0, 0, 0.48)",
    footerSurface: "rgba(8, 9, 11, 0.9)",
    footerBorder: "rgba(245, 247, 244, 0.1)",
  },
  component: {
    cardSurface: "rgba(15, 18, 21, 0.84)",
    cardSurfaceStrong: "rgba(12, 14, 17, 0.95)",
    cardBorder: "rgba(245, 247, 244, 0.12)",
    mediaSurface: "linear-gradient(180deg, rgba(19, 23, 26, 0.95), rgba(6, 8, 10, 0.98))",
    buttonBg: "linear-gradient(135deg, #0f8f50 0%, #0b6d3d 54%, #074424 100%)",
    buttonFg: "#f5f7f4",
    buttonBorder: "rgba(245, 247, 244, 0.16)",
  },
  layout: {
    containerWidth: "1220px",
    sectionY: "clamp(4.2rem, 7vw, 6.4rem)",
    sectionYMobile: "clamp(3rem, 8vw, 4rem)",
    containerX: "clamp(1rem, 3vw, 2rem)",
    gridGap: "clamp(1rem, 2vw, 1.4rem)",
    cardPadding: "clamp(1rem, 2vw, 1.4rem)",
  },
  radius: {
    sm: "14px",
    md: "20px",
    lg: "30px",
    xl: "42px",
    pill: "999px",
  },
  shadow: {
    soft: "0 16px 50px rgba(0, 0, 0, 0.24)",
    card: "0 28px 78px rgba(0, 0, 0, 0.38)",
    hero: "0 40px 96px rgba(0, 0, 0, 0.5)",
    glow: "0 0 40px rgba(210, 52, 73, 0.18)",
  },
  type: {
    display: "clamp(3rem, 7vw, 5.8rem)",
    heading: "clamp(2rem, 5vw, 3.35rem)",
    subheading: "clamp(1rem, 2vw, 1.18rem)",
    cardTitle: "clamp(1.14rem, 2vw, 1.46rem)",
    bodyLg: "clamp(1.05rem, 2vw, 1.2rem)",
    body: "clamp(0.96rem, 1.4vw, 1.06rem)",
    label: "0.78rem",
    meta: "0.88rem",
    metric: "clamp(1.7rem, 3vw, 2.4rem)",
    metricSecondary: "0.92rem",
    stat: "clamp(1.18rem, 2vw, 1.5rem)",
  },
  motion: {
    fast: "220ms",
    base: "420ms",
    slow: "760ms",
    loop: "5200ms",
  },
} as const;

type ThemeVars = Record<`--${string}`, string>;

function createThemeVariables() {
  const vars: ThemeVars = {
    "--flag-black": sudanTheme.flag.black,
    "--flag-black-rgb": sudanTheme.flag.blackRgb,
    "--flag-white": sudanTheme.flag.white,
    "--flag-white-rgb": sudanTheme.flag.whiteRgb,
    "--flag-red": sudanTheme.flag.red,
    "--flag-red-rgb": sudanTheme.flag.redRgb,
    "--flag-green": sudanTheme.flag.green,
    "--flag-green-rgb": sudanTheme.flag.greenRgb,
    "--tone-deep-rgb": sudanTheme.tone.deepRgb,
    "--tone-surface-rgb": sudanTheme.tone.surfaceRgb,
    "--tone-raised-rgb": sudanTheme.tone.raisedRgb,
    "--color-bg": sudanTheme.color.bg,
    "--color-bg-top": sudanTheme.color.bgTop,
    "--color-bg-deep": sudanTheme.color.bgDeep,
    "--color-foreground": sudanTheme.color.foreground,
    "--color-foreground-soft": sudanTheme.color.foregroundSoft,
    "--color-muted": sudanTheme.color.muted,
    "--color-primary": sudanTheme.color.primary,
    "--color-primary-soft": sudanTheme.color.primarySoft,
    "--color-primary-strong": sudanTheme.color.primaryStrong,
    "--color-secondary": sudanTheme.color.secondary,
    "--color-secondary-soft": sudanTheme.color.secondarySoft,
    "--color-surface": sudanTheme.color.surface,
    "--color-surface-strong": sudanTheme.color.surfaceStrong,
    "--color-surface-accent": sudanTheme.color.surfaceAccent,
    "--color-surface-media": sudanTheme.color.surfaceMedia,
    "--color-border-soft": sudanTheme.color.borderSoft,
    "--color-border-strong": sudanTheme.color.borderStrong,
    "--color-grid-line": sudanTheme.color.gridLine,
    "--color-glow": sudanTheme.color.glow,
    "--header-surface": sudanTheme.chrome.headerSurface,
    "--header-border": sudanTheme.chrome.headerBorder,
    "--header-shadow": sudanTheme.chrome.headerShadow,
    "--footer-surface": sudanTheme.chrome.footerSurface,
    "--footer-border": sudanTheme.chrome.footerBorder,
    "--card-surface": sudanTheme.component.cardSurface,
    "--card-surface-strong": sudanTheme.component.cardSurfaceStrong,
    "--card-border": sudanTheme.component.cardBorder,
    "--media-surface": sudanTheme.component.mediaSurface,
    "--button-bg": sudanTheme.component.buttonBg,
    "--button-fg": sudanTheme.component.buttonFg,
    "--button-border": sudanTheme.component.buttonBorder,
    "--container-width": sudanTheme.layout.containerWidth,
    "--section-y": sudanTheme.layout.sectionY,
    "--section-y-mobile": sudanTheme.layout.sectionYMobile,
    "--container-x": sudanTheme.layout.containerX,
    "--grid-gap": sudanTheme.layout.gridGap,
    "--card-padding": sudanTheme.layout.cardPadding,
    "--radius-sm": sudanTheme.radius.sm,
    "--radius-md": sudanTheme.radius.md,
    "--radius-lg": sudanTheme.radius.lg,
    "--radius-xl": sudanTheme.radius.xl,
    "--radius-pill": sudanTheme.radius.pill,
    "--shadow-soft": sudanTheme.shadow.soft,
    "--shadow-card": sudanTheme.shadow.card,
    "--shadow-hero": sudanTheme.shadow.hero,
    "--shadow-glow": sudanTheme.shadow.glow,
    "--display-role": sudanTheme.type.display,
    "--heading-role": sudanTheme.type.heading,
    "--subheading-role": sudanTheme.type.subheading,
    "--card-title-role": sudanTheme.type.cardTitle,
    "--body-lg-role": sudanTheme.type.bodyLg,
    "--body-role": sudanTheme.type.body,
    "--label-role": sudanTheme.type.label,
    "--meta-role": sudanTheme.type.meta,
    "--metric-role": sudanTheme.type.metric,
    "--metric-secondary-role": sudanTheme.type.metricSecondary,
    "--stat-role": sudanTheme.type.stat,
    "--motion-fast": sudanTheme.motion.fast,
    "--motion-base": sudanTheme.motion.base,
    "--motion-slow": sudanTheme.motion.slow,
    "--motion-loop": sudanTheme.motion.loop,
  };

  return vars;
}

export const sudanThemeVars = createThemeVariables() as CSSProperties;

export { sudanTheme };
